POST http://localhost:8080/api/pos
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"id":0,"vendorid":1, "amount": 3333.048,"podate": "", "items":[{"id":0, "poid":0,"price": 129.97,"qty":10,"productid": "AD843","productname":""},{"id":0, "poid":0,"price": 229.97,"qty":10,"productid": "AD842","productname":""},{"id": 0,"poid":0, "price":329.98,"qty":5, "productid": "AD841","productname":""}]}
###
